name: openml-tutorial
dependencies:
  # Core scientific python
  - python>=3.6
  - numpy>=1.6.2
  - scipy>=0.13.3
  - matplotlib>=2.2.2
  - pandas>=0.22.0
  - scikit-learn>=0.20
  - seaborn>=0.8.1
  - pprint>=0.1
  - jupyter>=1.0.0
  - pip:
    - openml>=0.8.0
